site_name: TTLocVis
nav:
    - Home: home.md
    - Classes and Methods: classes_methods.md
    - Covariates available after instancing a "Cleaner"-object: covariates_cleaner_object.md
    - Usage and Examples: examples.md
theme: readthedocs